// packages/react-mfe/src/App.tsx
﻿import React, { useState, useEffect } from 'react';

const App: React.FC = () => {
  const [counter, setCounter] = useState(0);
  const [lastSource, setLastSource] = useState<string>('');

  useEffect(() => {
    // Access shared services from window (provided by shell)
    const sharedServices = (window as any).sharedServices;
    const counterActions = sharedServices?.counterActions;
    const eventBus = sharedServices?.eventBus;

    if (counterActions && eventBus) {
      // Initialize with current value
      setCounter(counterActions.getValue());

      // Subscribe to counter changes from any MFE
      const unsubscribe = counterActions.subscribe((value: number) => {
        setCounter(value);
      });

      // Also listen to event bus for source tracking
      const unsubscribeEvents = eventBus.onAll((payload: any) => {
        if (payload.type.startsWith('counter-')) {
          setLastSource(payload.source);
        }
      });

      return () => {
        unsubscribe();
        unsubscribeEvents();
      };
    } else {
      console.warn('⚠️ React MFE: Shared services not available');
    }
  }, []);

  const handleIncrement = () => {
    const counterActions = (window as any).sharedServices?.counterActions;
    if (counterActions) {
      counterActions.increment('react-mfe');
    }
  };

  const handleDecrement = () => {
    const counterActions = (window as any).sharedServices?.counterActions;
    if (counterActions) {
      counterActions.decrement('react-mfe');
    }
  };

  const handleReset = () => {
    const counterActions = (window as any).sharedServices?.counterActions;
    if (counterActions) {
      counterActions.reset('react-mfe');
    }
  };

  return (
    <div style={{ 
      padding: '20px', 
      fontFamily: 'Arial, sans-serif',
      backgroundColor: '#f0f8ff'
    }}>
      <header style={{ 
        marginBottom: '30px',
        padding: '20px',
        backgroundColor: '#007bff',
        color: 'white',
        borderRadius: '8px'
      }}>
        <h1 style={{ margin: 0 }}>React MFE - User Management</h1>
        <p style={{ margin: '10px 0 0 0' }}>Single-SPA React Micro-Frontend</p>
      </header>
      
      <main>
        <div style={{ 
          backgroundColor: 'white',
          padding: '20px',
          borderRadius: '8px',
          boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
          marginBottom: '20px'
        }}>
          <h2 style={{ color: '#333', marginBottom: '15px' }}>User Management Dashboard</h2>
          <p style={{ color: '#666', lineHeight: '1.6' }}>
            This is the React micro-frontend responsible for user authentication, 
            user profiles, and session management within the Single-SPA ecosystem.
          </p>
        </div>

        {/* Cross-MFE Communication Demo */}
        <div style={{ 
          backgroundColor: '#fff3cd',
          padding: '20px',
          borderRadius: '8px',
          boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
          border: '2px solid #ffc107'
        }}>
          <h3 style={{ color: '#856404', marginTop: 0 }}>
            🔗 Cross-MFE Counter Demo
          </h3>
          <p style={{ color: '#856404', fontSize: '14px' }}>
            Actions here update counters in Vue & Angular MFEs in real-time!
          </p>
          
          <div style={{ 
            display: 'flex', 
            alignItems: 'center', 
            gap: '15px',
            marginTop: '20px'
          }}>
            <button
              onClick={handleDecrement}
              style={{
                padding: '10px 20px',
                fontSize: '18px',
                backgroundColor: '#dc3545',
                color: 'white',
                border: 'none',
                borderRadius: '5px',
                cursor: 'pointer',
                fontWeight: 'bold'
              }}
            >
              -
            </button>
            
            <div style={{
              fontSize: '32px',
              fontWeight: 'bold',
              color: '#007bff',
              minWidth: '80px',
              textAlign: 'center',
              padding: '10px',
              backgroundColor: 'white',
              borderRadius: '5px',
              border: '2px solid #007bff'
            }}>
              {counter}
            </div>
            
            <button
              onClick={handleIncrement}
              style={{
                padding: '10px 20px',
                fontSize: '18px',
                backgroundColor: '#28a745',
                color: 'white',
                border: 'none',
                borderRadius: '5px',
                cursor: 'pointer',
                fontWeight: 'bold'
              }}
            >
              +
            </button>
            
            <button
              onClick={handleReset}
              style={{
                padding: '10px 20px',
                fontSize: '14px',
                backgroundColor: '#6c757d',
                color: 'white',
                border: 'none',
                borderRadius: '5px',
                cursor: 'pointer'
              }}
            >
              Reset
            </button>
          </div>

          {lastSource && (
            <p style={{ 
              marginTop: '15px', 
              fontSize: '12px', 
              color: '#856404',
              fontStyle: 'italic'
            }}>
              Last updated by: <strong>{lastSource}</strong>
            </p>
          )}
        </div>
      </main>
    </div>
  );
};

export default App;

// packages/vue-mfe/src/App.vue
﻿<template>
  <div class="vue-mfe">
    <header class="vue-header">
      <h1>Vue MFE - Products</h1>
      <p>Single-SPA Vue 3 Micro-Frontend</p>
    </header>

    <main class="vue-content">
      <div class="info-card">
        <h2>Product Catalog</h2>
        <p>
          This is the Vue micro-frontend responsible for product listings,
          shopping cart, and e-commerce functionality.
        </p>
      </div>

      <!-- Cross-MFE Communication Demo -->
      <div class="counter-demo">
        <h3>🔗 Cross-MFE Counter Display</h3>
        <p class="demo-description">
          This counter syncs with React & Angular MFEs in real-time!
        </p>

        <div class="counter-display">
          <div class="counter-badge">{{ counter }}</div>
        </div>

        <p v-if="lastSource" class="last-update">
          Last updated by: <strong>{{ lastSource }}</strong>
        </p>

        <div class="action-hint">
          💡 Go to React MFE to change the counter and watch it update here!
        </div>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';

// Access shared services from window (provided by shell)
const sharedServices = (window as any).sharedServices;
const counterActions = sharedServices?.counterActions;
const eventBus = sharedServices?.eventBus;

const counter = ref(0);
const lastSource = ref('');

let unsubscribeCounter: (() => void) | null = null;
let unsubscribeEvents: (() => void) | null = null;

onMounted(() => {
  if (counterActions && eventBus) {
    // Initialize with current value
    counter.value = counterActions.getValue();

    // Subscribe to counter changes
    unsubscribeCounter = counterActions.subscribe((value: number) => {
      counter.value = value;
    });

    // Track source of updates
    unsubscribeEvents = eventBus.onAll((payload: any) => {
      if (payload.type.startsWith('counter-')) {
        lastSource.value = payload.source;
      }
    });

    console.log('✅ Vue MFE: Connected to shared counter state');
  } else {
    console.warn('⚠️ Vue MFE: Shared services not available');
  }
});

onUnmounted(() => {
  if (unsubscribeCounter) unsubscribeCounter();
  if (unsubscribeEvents) unsubscribeEvents();
});
</script>

<style scoped>
.vue-mfe {
  padding: 20px;
  font-family: Arial, sans-serif;
  background-color: #f0fff0;
  min-height: 100vh;
}

.vue-header {
  margin-bottom: 30px;
  padding: 20px;
  background: linear-gradient(135deg, #42b883 0%, #35495e 100%);
  color: white;
  border-radius: 8px;
  text-align: center;
}

.vue-header h1 {
  margin: 0;
  font-size: 28px;
}

.vue-header p {
  margin: 10px 0 0 0;
  opacity: 0.9;
}

.vue-content {
  max-width: 800px;
  margin: 0 auto;
}

.info-card {
  background-color: white;
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  margin-bottom: 20px;
}

.info-card h2 {
  color: #333;
  margin-bottom: 15px;
}

.info-card p {
  color: #666;
  line-height: 1.6;
}

.counter-demo {
  background-color: #d4edda;
  padding: 25px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  border: 2px solid #42b883;
  text-align: center;
}

.counter-demo h3 {
  color: #155724;
  margin-top: 0;
}

.demo-description {
  color: #155724;
  font-size: 14px;
  margin-bottom: 20px;
}

.counter-display {
  display: flex;
  justify-content: center;
  margin: 20px 0;
}

.counter-badge {
  font-size: 48px;
  font-weight: bold;
  color: #42b883;
  min-width: 120px;
  padding: 20px;
  background-color: white;
  border-radius: 10px;
  border: 3px solid #42b883;
  box-shadow: 0 4px 6px rgba(0,0,0,0.1);
}

.last-update {
  margin-top: 15px;
  font-size: 12px;
  color: #155724;
  font-style: italic;
}

.action-hint {
  margin-top: 15px;
  padding: 10px;
  background-color: rgba(255, 255, 255, 0.5);
  border-radius: 5px;
  font-size: 13px;
  color: #155724;
}
</style>
